#!/usr/bin/env bash
# superagent-tick.sh — fire exactly ONE external-mode superagent tick in a FRESH
# CLI session (no context accumulation across ticks). Invoked by an OS scheduler
# (systemd user timer / cron). Runs the tick via `claude -p`.
#
# All loop state lives in the gitignored loop-status file, so every tick is
# stateless: read the file, run one tick, write the file, exit. Never resume a
# prior session — a fresh process per tick is what keeps the context bounded and
# lets the loop run straight through to DONE (see superloop L4: the context
# handoff gate is a no-op in external mode).
#
# Inputs (env or args; env wins for scheduler use):
#   LOOP_FILE     absolute path to the loop-status file (or $1)
#   REPO          primary checkout root                    (default: derived)
#   TICK_TIMEOUT  optional per-tick wall-clock cap, seconds (default: none/unlimited)
#   LOG_FILE      driver log path                          (default: /tmp/superagent-<loop>.log)
set -euo pipefail
ts() { date -u +%Y-%m-%dT%H:%M:%SZ; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO="${REPO:-$(git rev-parse --show-toplevel 2>/dev/null || true)}"
[[ -n "$REPO" ]] || { echo "superagent: set REPO or run from inside the target repo" >&2; exit 1; }

LOOP_FILE="${LOOP_FILE:-${1:-}}"
if [[ -z "$LOOP_FILE" ]]; then
  echo "superagent-tick: LOOP_FILE not set (pass as \$1 or env)" >&2
  exit 2
fi

# Optional per-tick wall-clock cap. When TICK_TIMEOUT is a positive integer, wrap
# the CLI in `timeout`; otherwise (unset/empty/0/none) run with NO cap so long
# CI-push ticks are never killed mid-flight. The overlap lock (L3) still serializes
# ticks, so an uncapped tick is safe.
TICK_TIMEOUT="${TICK_TIMEOUT:-}"
TIMEOUT_CMD=()
if [[ "$TICK_TIMEOUT" =~ ^[1-9][0-9]*$ ]]; then
  TIMEOUT_CMD=(timeout "$TICK_TIMEOUT")
fi
LOG_FILE="${LOG_FILE:-/tmp/superagent-$(basename "$LOOP_FILE" .md).log}"
# Output format: stream (default) = live incremental console output; text = final only.
TICK_OUTPUT_FORMAT="${TICK_OUTPUT_FORMAT:-stream}"

# Load the API key from .env (repo policy: keys live in .env only).
if [[ -f "$REPO/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  . "$REPO/.env"
  set +a
fi

# Ensure gh is authenticated and export GH_TOKEN so the CLI child inherits it
# (the tick's sandbox blocks gh from reading its own config). Fail LOUDLY if not,
# so a misconfigured host does not silently break every superrun CI/PR step.
# shellcheck source=_common.sh
. "$SCRIPT_DIR/_common.sh"
load_superenv "$REPO"

# --- WAITING FOR INPUT gate ---------------------------------------------------
# A loop parked on WAITING FOR INPUT resumes only when a human writes
# `answer: <option>` under ## Pending decision. Until then every scheduler fire
# used to launch a full paid CLI session that read the file, found no answer, and
# exited — the same no-op-per-interval waste #18 fixed for DONE. Poll the file in
# bash instead: no answer → log one line, exit 0 (a legal clean no-op under the
# L2 teardown invariant), no session. The moment an answer appears the next fire
# runs the session as before (or answer.sh kicks one immediately). Runs BEFORE
# the gh/CLI preflight so a parked loop costs nothing at all. Opt out with
# SUPER_INPUT_GATE=false.
if [[ "${SUPER_INPUT_GATE:-true}" == true && \
      "$(superagent_loop_status "$LOOP_FILE")" == "WAITING FOR INPUT" ]] && \
   ! superagent_pending_answer "$LOOP_FILE" >/dev/null; then
  echo "=== $(ts) superagent-tick: loop is WAITING FOR INPUT with no answer — skipping the session (SUPER_INPUT_GATE). Answer + resume now: $SCRIPT_DIR/answer.sh ${SUPERAGENT_SLUG:-<slug>} \"<option>\" ===" >>"$LOG_FILE"
  exit 0
fi

# Which agent CLI drives the tick: SUPER_HARNESS=claude (default) | cursor | codex.
# Put the right binary on PATH (systemd/cron use a minimal PATH without
# ~/.local/bin) and fail fast if it's still missing, then verify gh auth.
HARNESS="$(superagent_harness)" || exit 6
ensure_cli_bin || exit 5
ensure_gh_auth || exit 4

if [[ "$HARNESS" == cursor ]]; then
  # Cursor build of the plugin: skills live under <plugin-repo>/cursor (generated
  # by scripts/build-cursor-skills.sh); pass it as --plugin-dir so the loop's
  # internal superplan/superrun skill dispatches resolve.
  SKILLS_ROOT="$PLUGIN_ROOT/cursor"
  if [[ ! -f "$SKILLS_ROOT/skills/superagent/SKILL.md" ]]; then
    echo "superagent-tick: Cursor build missing at $SKILLS_ROOT (run scripts/build-cursor-skills.sh)" >&2
    exit 7
  fi
  # Model: TICK_MODEL > SUPER_MODEL_SUPERVISOR; values are Cursor model names
  # (agent --list-models). "inherit" -> empty -> omit --model (the CLI's own
  # default, "auto", applies).
  TICK_MODEL="${TICK_MODEL:-${SUPER_MODEL_SUPERVISOR:-inherit}}"
  [[ "$TICK_MODEL" == "inherit" ]] && TICK_MODEL=""
elif [[ "$HARNESS" == codex ]]; then
  # Codex build of the plugin: a Codex plugin-marketplace tree under <plugin-repo>/codex
  # (generated by scripts/build-codex-skills.sh). Skills load via the INSTALLED plugin
  # (codex plugin marketplace add <repo>/codex && codex plugin add superagent@superagent);
  # the tick itself only needs the SKILL.md file path for its file-read prompt.
  SKILLS_ROOT="$PLUGIN_ROOT/codex"
  if [[ ! -f "$SKILLS_ROOT/plugins/superagent/skills/superagent/SKILL.md" ]]; then
    echo "superagent-tick: Codex build missing at $SKILLS_ROOT (run scripts/build-codex-skills.sh)" >&2
    exit 7
  fi
  # Model: TICK_MODEL > SUPER_MODEL_SUPERVISOR; values are Codex model names.
  # "inherit" -> empty -> omit -m (the CLI's config.toml default applies).
  TICK_MODEL="${TICK_MODEL:-${SUPER_MODEL_SUPERVISOR:-inherit}}"
  [[ "$TICK_MODEL" == "inherit" ]] && TICK_MODEL=""
else
  SKILLS_ROOT="$PLUGIN_ROOT"
  # Model: always passed explicitly (--model) so the tick uses THIS model regardless
  # of the CLI's own configured default.
  # TICK_MODEL > SUPER_MODEL_SUPERVISOR > opus; a headless tick has no session
  # model, so "inherit" also resolves to opus.
  TICK_MODEL="${TICK_MODEL:-${SUPER_MODEL_SUPERVISOR:-opus}}"
  [[ "$TICK_MODEL" == "inherit" ]] && TICK_MODEL="opus"
fi

# Supervisor reasoning effort: TICK_EFFORT > SUPER_EFFORT_SUPERVISOR > inherit.
# Harness-native names (claude: low..max; codex: none..xhigh); inherit -> pass nothing.
# Cursor has no effort control: warn and drop.
TICK_EFFORT="${TICK_EFFORT:-${SUPER_EFFORT_SUPERVISOR:-inherit}}"
[[ "$TICK_EFFORT" == "inherit" ]] && TICK_EFFORT=""
if [[ "$HARNESS" == cursor && -n "$TICK_EFFORT" ]]; then
  echo "superagent-tick: warning — reasoning effort is not supported on the Cursor CLI; ignoring '$TICK_EFFORT'" >&2
  TICK_EFFORT=""
fi
# CLAUDE_CODE_EFFORT_LEVEL outranks both --effort and per-role frontmatter pins —
# never set it here, and flag it when the scheduler env already carries it.
if [[ "$HARNESS" == claude && -n "${CLAUDE_CODE_EFFORT_LEVEL:-}" ]]; then
  echo "superagent-tick: warning — CLAUDE_CODE_EFFORT_LEVEL='$CLAUDE_CODE_EFFORT_LEVEL' is set; it overrides --effort AND per-role effort pins" >&2
fi
# Codex sandbox posture (codex harness only): danger-full-access (default) | workspace-write.
# danger-full-access is parity with the claude harness (which runs unsandboxed): codex's
# workspace-write keeps the repo's top-level .git/ read-only (no allow_git_writes knob as of
# codex-cli 0.147.0), so git fetch/commit fail and the L5 sync gate parks the loop on tick 1.
if [[ "$HARNESS" == codex ]]; then
  SUPER_CODEX_SANDBOX="${SUPER_CODEX_SANDBOX:-danger-full-access}"
  case "$SUPER_CODEX_SANDBOX" in
    workspace-write|danger-full-access) ;;
    *) echo "superagent-tick: bad SUPER_CODEX_SANDBOX '$SUPER_CODEX_SANDBOX' (want workspace-write|danger-full-access)" >&2; exit 8 ;;
  esac
fi

# Slash commands are unavailable in headless print mode, so open the skill file
# directly (superloop L2, Driver B) rather than invoking it by name — on Cursor a
# disable-model-invocation skill is invisible to model-driven lookup (verified),
# and on Claude Code the Skill-tool semantics in headless print mode are
# unverified, so the proven file-read entry point is used on both. The loop's own
# internal superagent:superplan / superagent:superrun dispatches still go through
# the skill mechanism once the session is running, so the plugin must still be
# installed AND enabled (or passed via --plugin-dir on Cursor) for this headless
# session. Non-interactive: the tick must never block on a question.
if [[ "$HARNESS" == claude ]]; then
  PROMPT="Read ${SKILLS_ROOT}/skills/superagent/SKILL.md and execute exactly ONE --tick on loop file ${LOOP_FILE}, in unattended/non-interactive mode: NEVER call AskQuestion/AskUserQuestion, and NEVER end the session with a question as your final message — no one can answer a headless session. If a decision needs the user, write the ## Pending decision block, set status to WAITING FOR INPUT, and exit per the skill; if your dispatch is interrupted mid-flight, restore the transient status to its ready state per the skill's crash-recovery mapping, release the lock, and exit — never leave status PLANNING or RUNNING at exit. Then stop."
else
  # cursor + codex: same invariants; generic wording (no Ask* tools in these harnesses).
  SUPERVISOR_SKILL="$SKILLS_ROOT/skills/superagent/SKILL.md"
  [[ "$HARNESS" == codex ]] && SUPERVISOR_SKILL="$SKILLS_ROOT/plugins/superagent/skills/superagent/SKILL.md"
  PROMPT="Read ${SUPERVISOR_SKILL} and execute exactly ONE --tick on loop file ${LOOP_FILE}, in unattended/non-interactive mode: NEVER ask the user a question in chat, and NEVER end the session with a question as your final message — no one can answer a headless session. If a decision needs the user, write the ## Pending decision block, set status to WAITING FOR INPUT, and exit per the skill; if your dispatch is interrupted mid-flight, restore the transient status to its ready state per the skill's crash-recovery mapping, release the lock, and exit — never leave status PLANNING or RUNNING at exit. Then stop."
fi

# --- L3 lock safety net (issue #15) -----------------------------------------
# The overlap lock is acquired/released by the AGENT inside the session
# (superloop L3). If the CLI kills the session mid-flight (background-wait
# ceiling, crash, OOM), release_lock() never runs and the leaked lock wedges the
# loop until the SUPER_LOCK_STEAL_MIN (90 min) steal window expires. The wrapper
# outlives the session, so it is the safety net: acquire_lock() records
# $SUPERAGENT_TICK_PID (this wrapper's PID, exported here) in <lockdir>/owner,
# and the EXIT trap reaps the lock ONLY when the owner file names this very tick
# — a wrapper that exited early on the held-lock path must never reap a peer's
# live lock.
LOCK_DIR="$(dirname "$LOOP_FILE")/.$(basename "$LOOP_FILE").lockd"
export SUPERAGENT_TICK_PID=$$
reap_own_lock() {
  if [[ -d "$LOCK_DIR" && "$(cat "$LOCK_DIR/owner" 2>/dev/null)" == "$$" ]]; then
    echo "=== $(ts) superagent-tick reaping leaked L3 lock (session ended before release_lock): $LOCK_DIR ===" >>"$LOG_FILE"
    rm -rf "$LOCK_DIR"
  fi
}
trap reap_own_lock EXIT
# A signal received while waiting on the CLI child must still run the EXIT trap
# (bash skips it for a fatal unhandled signal).
trap 'exit 143' TERM
trap 'exit 130' INT

echo "=== $(ts) superagent-tick harness=${HARNESS} model=${TICK_MODEL:-default} effort=${TICK_EFFORT:-default} sandbox=${SUPER_CODEX_SANDBOX:-n/a} output=${TICK_OUTPUT_FORMAT} loop=${LOOP_FILE} timeout=${TICK_TIMEOUT:-none} ===" >>"$LOG_FILE"
# Not probed (no live check) — the prompt below reads skills/superagent/SKILL.md
# directly at SKILLS_ROOT. The loop's own internal superagent:superplan /
# superagent:superrun dispatches still go through the skill mechanism once
# running, so the plugin must still be installed AND enabled (claude) or passed
# via --plugin-dir (cursor) for this headless session. If the tick fails
# opaquely, check both: the file exists at SKILLS_ROOT, and the plugin resolves.
echo "    requires: superagent plugin resolvable for this session (tick entry reads skills/superagent/SKILL.md directly at ${SKILLS_ROOT}; superplan / superrun still resolved via the skill mechanism)" >>"$LOG_FILE"

# API auth: a key in $REPO/.env (repo policy) when present — ANTHROPIC_API_KEY
# (claude) / CURSOR_API_KEY (cursor) / OPENAI_API_KEY (codex); otherwise fall
# through to the CLI's own stored login (subscription/OAuth hosts have no separate
# key; codex: `codex login`). If neither exists the CLI itself fails with a clear
# auth error, logged below — so warn, don't abort.
if [[ "$HARNESS" == cursor && -z "${CURSOR_API_KEY:-}" ]]; then
  echo "    note: CURSOR_API_KEY not set (no $REPO/.env entry); relying on the Cursor CLI's own stored login" >>"$LOG_FILE"
elif [[ "$HARNESS" == codex && -z "${OPENAI_API_KEY:-}" ]]; then
  echo "    note: OPENAI_API_KEY not set (no $REPO/.env entry); relying on the Codex CLI's own stored login" >>"$LOG_FILE"
elif [[ "$HARNESS" == claude && -z "${ANTHROPIC_API_KEY:-}" ]]; then
  echo "    note: ANTHROPIC_API_KEY not set (no $REPO/.env entry); relying on the claude CLI's own stored login" >>"$LOG_FILE"
fi

# Status AND pending-decision text on entry, so post-run hooks can detect a
# transition (notify once on parking/finishing, never on every subsequent fire)
# — and also a RE-park: a tick that consumes an answer and immediately parks on
# a NEW question leaves the status identical on both sides, so the status alone
# would miss it and the gate would then silently suppress every later session.
status_before="$(superagent_loop_status "$LOOP_FILE")"
pending_before="$(superagent_pending_section "$LOOP_FILE")"

# Bytes already in the log before this tick, so post-run checks only scan THIS
# tick's segment (a prior tick's output must not poison this one's verdict).
log_bytes_before="$(wc -c <"$LOG_FILE" 2>/dev/null || echo 0)"

rc=0
if [[ "$HARNESS" == codex ]]; then
  codex_args=(exec "$PROMPT")
  if [[ "$SUPER_CODEX_SANDBOX" == workspace-write ]]; then
    codex_args+=(--sandbox workspace-write -c sandbox_workspace_write.network_access=true)
  else
    codex_args+=(--dangerously-bypass-approvals-and-sandbox)
  fi
  [[ -n "$TICK_MODEL" ]]  && codex_args+=(-m "$TICK_MODEL")
  [[ -n "$TICK_EFFORT" ]] && codex_args+=(-c "model_reasoning_effort=$TICK_EFFORT")
  [[ "$TICK_OUTPUT_FORMAT" == stream ]] && codex_args+=(--json)
  ( cd "$REPO" && "${TIMEOUT_CMD[@]+"${TIMEOUT_CMD[@]}"}" codex "${codex_args[@]}" ) \
    >>"$LOG_FILE" 2>&1 || rc=$?
elif [[ "$HARNESS" == cursor ]]; then
  # Cursor CLI: --trust (headless workspace trust) + --force (unattended tool
  # approval); the plugin rides --plugin-dir. Model only when pinned (default: auto).
  cursor_args=(-p "$PROMPT" --trust --force --plugin-dir "$SKILLS_ROOT")
  [[ -n "$TICK_MODEL" ]] && cursor_args+=(--model "$TICK_MODEL")
  if [[ "$TICK_OUTPUT_FORMAT" == stream ]]; then
    cursor_args+=(--output-format stream-json)
  else
    cursor_args+=(--output-format text)
  fi
  ( cd "$REPO" && "${TIMEOUT_CMD[@]+"${TIMEOUT_CMD[@]}"}" "$SUPERAGENT_CURSOR_BIN" "${cursor_args[@]}" ) \
    >>"$LOG_FILE" 2>&1 || rc=$?
else
  # The tick's whole job is to dispatch ONE heavy skill (superrun/superplan) into
  # a subagent and await its Final Report — routinely far longer than print
  # mode's default 600s background-task wait ceiling, which would terminate the
  # subagents mid-flight while the tick still exits 0 (issue #15). Lift the
  # ceiling by default (0 = wait indefinitely), mirroring TICK_TIMEOUT's
  # unlimited-by-default policy; an operator-set value is respected. This lives
  # in the shipped script, not the per-goal env file, because install-timer.sh
  # rewrites that file from scratch on every re-arm.
  export CLAUDE_CODE_PRINT_BG_WAIT_CEILING_MS="${CLAUDE_CODE_PRINT_BG_WAIT_CEILING_MS:-0}"
  claude_args=(-p "$PROMPT" --model "$TICK_MODEL" --allowedTools "Read,Edit,Write,Bash,Task,Skill")
  [[ -n "$TICK_EFFORT" ]] && claude_args+=(--effort "$TICK_EFFORT")
  [[ "$TICK_OUTPUT_FORMAT" == stream ]] && claude_args+=(--output-format stream-json --verbose)
  ( cd "$REPO" && "${TIMEOUT_CMD[@]+"${TIMEOUT_CMD[@]}"}" claude "${claude_args[@]}" ) \
    >>"$LOG_FILE" 2>&1 || rc=$?
fi

# A claude session that hits a background-wait ceiling (operator override — the
# default above is unlimited) kills the tick's subagents mid-flight and still
# exits 0: a silent abort that leaves status RUNNING and `exit=0` in the log.
# Detect the CLI's termination line in THIS tick's log segment and fail loudly,
# so exit=0 keeps meaning "the tick completed its work".
if [[ "$HARNESS" == claude && "$rc" -eq 0 ]] && \
   tail -c "+$((log_bytes_before + 1))" "$LOG_FILE" 2>/dev/null \
     | grep -q "Background tasks still running after"; then
  echo "=== $(ts) superagent-tick ERROR: session hit the print-mode background-task wait ceiling and was terminated mid-flight (see CLAUDE_CODE_PRINT_BG_WAIT_CEILING_MS) ===" >>"$LOG_FILE"
  rc=9
fi

# --- stranded-transient detection (issue #17) --------------------------------
# A session can also end "successfully" having done no work at all: a dispatch
# interrupted mid-flight (host sleep, API loss) can end its turn by asking the
# operator a question — a well-formed completion, exit 0 — leaving the loop
# file's transient status (PLANNING/RUNNING) persisted. The EXIT trap reaps the
# lock and the next tick's crash recovery heals the status, but exit=0 must
# keep meaning "the tick advanced or parked": a transient status after a rc=0
# session is a failed tick. Fail loudly (exit 10) so monitoring sees it.
# NOT flagged: a held-lock no-op — this wrapper overlapped a LIVE peer tick
# (lock owner is an alive PID that isn't ours), so the transient status on disk
# is the peer's normal in-flight state, not a stranding. A dead or absent owner
# gives the peer no such shield. The check is guarded (readable file, ||-safe
# pipelines) so set -e can never kill the wrapper here — the exit= log line and
# the DONE self-disarm below must always run.
if [[ "$rc" -eq 0 && -r "$LOOP_FILE" ]]; then
  final_status="$(sed -n 's/^status:[[:space:]]*//p' "$LOOP_FILE" 2>/dev/null | head -1 | sed 's/[[:space:]]*$//' || true)"
  case "$final_status" in
    PLANNING|RUNNING)
      lock_owner="$(cat "$LOCK_DIR/owner" 2>/dev/null || true)"
      if [[ -n "$lock_owner" && "$lock_owner" != "$$" ]] && kill -0 "$lock_owner" 2>/dev/null; then
        echo "=== $(ts) superagent-tick: held-lock no-op — peer tick (pid $lock_owner) is mid-flight; transient status '${final_status}' is the peer's, not a stranding ===" >>"$LOG_FILE"
      else
        echo "=== $(ts) superagent-tick ERROR: session ended with transient status '${final_status}' — the tick completed without advancing or parking (interrupted dispatch ended in a question? issue #17). The EXIT trap reaps any lock this tick still owns; the next tick self-heals via crash recovery. ===" >>"$LOG_FILE"
        rc=10
      fi
      ;;
  esac
fi

echo "=== $(ts) superagent-tick exit=${rc} ===" >>"$LOG_FILE"

# --- transition notifications -----------------------------------------------
# Tell the operator ONCE whenever this tick leaves the loop parked on a question
# they have not been shown, or finishes it (DONE).
#   DONE               → a status transition (entry status != exit status).
#   WAITING FOR INPUT  → a status transition into it, OR the `## Pending
#                        decision` block changed while already parked. The
#                        second arm is the re-park case: a tick that consumes
#                        `answer:` and immediately parks on a NEW question shows
#                        WAITING FOR INPUT on both sides, so a status-only guard
#                        would stay silent and the gate would then suppress
#                        every later session — a silently stranded loop.
# Still no sidecar state: an unchanged parked loop notifies nothing, and a gated
# fire exits long before this block, so repeats are impossible.
# SUPER_NOTIFY_CMD or the desktop notifier; see superagent_notify.
status_after="$(superagent_loop_status "$LOOP_FILE")"
pending_after="$(superagent_pending_section "$LOOP_FILE")"
notify_slug="${SUPERAGENT_SLUG:-$(basename "$LOOP_FILE" .md)}"
if [[ "$status_after" == "WAITING FOR INPUT" ]] && \
   { [[ "$status_before" != "$status_after" ]] || [[ "$pending_before" != "$pending_after" ]]; }; then
  superagent_notify waiting-for-input "$notify_slug" "$LOOP_FILE" >>"$LOG_FILE" 2>&1 || true
elif [[ "$status_after" == DONE && "$status_before" != "$status_after" ]]; then
  superagent_notify done "$notify_slug" "$LOOP_FILE" >>"$LOG_FILE" 2>&1 || true
fi

# --- DONE self-disarm (issue #18) -------------------------------------------
# status: DONE is terminal, but the scheduler entry keeps firing a full CLI
# session per interval forever — each a paid no-op — and the old "remind the
# user to disable the timer" landed in this log, which external mode guarantees
# nobody is watching. So once the loop file says DONE, the wrapper disarms its
# own scheduler entry via uninstall-timer.sh --from-tick (drain-wait skipped; on
# launchd the bootout is the final act and kills this very process, hence: run
# AFTER the session, log everything first, reap the lock ourselves). The env
# file and loop-status file are kept, so re-arming stays a one-liner. Runs on
# any exit rc — DONE is durable regardless of how this particular tick ended.
# Opt out with SUPER_AUTO_DISARM_ON_DONE=false (env or .superenv) to keep a
# deliberately polling loop.
if [[ "${SUPER_AUTO_DISARM_ON_DONE:-true}" == true && \
      "$(sed -n 's/^status:[[:space:]]*//p' "$LOOP_FILE" 2>/dev/null | head -1 | sed 's/[[:space:]]*$//')" == DONE ]]; then
  CONF_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/superagent"
  DISARM_SLUG=""
  # Registered slug: SUPERAGENT_SLUG from the per-goal env file (recorded by
  # install-timer.sh), else scan the registry for the entry naming THIS loop
  # file (loops armed before the key existed). Either way the LOOP_FILE match
  # is required — it is the guard against disarming a same-named entry that
  # drives a different loop.
  if [[ -n "${SUPERAGENT_SLUG:-}" && \
        "$(sed -n 's/^LOOP_FILE=//p' "$CONF_DIR/${SUPERAGENT_SLUG}.env" 2>/dev/null | head -1)" == "$LOOP_FILE" ]]; then
    DISARM_SLUG="$SUPERAGENT_SLUG"
  else
    for envf in "$CONF_DIR"/*.env; do
      [[ -f "$envf" ]] || continue
      if [[ "$(sed -n 's/^LOOP_FILE=//p' "$envf" | head -1)" == "$LOOP_FILE" ]]; then
        DISARM_SLUG="$(basename "$envf" .env)"
        break
      fi
    done
  fi
  if [[ -n "$DISARM_SLUG" ]]; then
    echo "=== $(ts) superagent-tick: loop is DONE — self-disarming scheduler entry '$DISARM_SLUG' (SUPER_AUTO_DISARM_ON_DONE). Loop-status + env file kept; re-arm: $SCRIPT_DIR/install-timer.sh $DISARM_SLUG $LOOP_FILE ===" >>"$LOG_FILE"
    reap_own_lock   # the launchd bootout below can SIGKILL us before the EXIT trap runs
    "$SCRIPT_DIR/uninstall-timer.sh" "$DISARM_SLUG" --from-tick >>"$LOG_FILE" 2>&1 || \
      echo "=== $(ts) superagent-tick: WARNING — self-disarm failed; disable the scheduler entry manually (uninstall-timer.sh $DISARM_SLUG) ===" >>"$LOG_FILE"
  else
    echo "=== $(ts) superagent-tick: loop is DONE but no registered scheduler entry names this loop file — skipping self-disarm; disable your scheduler entry manually ===" >>"$LOG_FILE"
  fi
fi

exit "$rc"
